apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-server
  template:
    metadata:
      labels:
        app: simple-server
    spec:
      containers:
        - name: server1
          image: cholick/simple-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: CONTENT
              value: Running on 8080
            - name: PORT
              value: "8080"
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
        - name: server2
          image: cholick/simple-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: CONTENT
              value: Running on 9000
            - name: PORT
              value: "9000"
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "uid"
                fieldRef:
                  fieldPath: metadata.uid
              - path: "name"
                fieldRef:
                  fieldPath: metadata.name
